# Generated by Django 5.1.2 on 2024-12-19 20:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_ylwpgw', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
