# Generated by Django 5.1.2 on 2024-10-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
