# Generated by Django 5.1.2 on 2024-10-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_goal_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
