# Generated by Django 5.1.2 on 2024-11-04 18:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['deadline', '-created_at']},
        ),
        migrations.AddField(
            model_name='goal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='default_profile_ylwpgw', max_length=255, verbose_name='image'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'type'], name='api_goal_user_id_78b8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['deadline'], name='api_goal_deadlin_c75a31_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['completed'], name='api_goal_complet_558fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='api_userpro_created_bbce8a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='api_userpro_user_id_ea9cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['gender'], name='api_userpro_gender_03560e_idx'),
        ),
    ]
