# Generated by Django 5.1.2 on 2024-11-07 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_goal_options_goal_completed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='goal',
            name='api_goal_user_id_78b8bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='api_goal_deadlin_c75a31_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='api_goal_complet_558fc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='api_userpro_created_bbce8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='api_userpro_user_id_ea9cd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='api_userpro_gender_03560e_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fitness_goals',
        ),
        migrations.AddField(
            model_name='goal',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
