# Generated by Django 5.1.2 on 2024-11-18 20:01

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Workout', help_text='Title of the workout', max_length=200)),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('sports', 'Sports'), ('other', 'Other')], db_index=True, max_length=100)),
                ('date_logged', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the workout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], db_index=True, default='moderate', max_length=20)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['-date_logged', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments_workouts', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Comment',
                'verbose_name_plural': 'Workout Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_likes_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_likes_workouts', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Like',
                'verbose_name_plural': 'Workout Likes',
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date_logged'], name='workouts_wo_user_id_dd8bda_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['workout_type', 'intensity'], name='workouts_wo_workout_b4687e_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutcomment',
            index=models.Index(fields=['user', 'workout', 'created_at'], name='workouts_wo_user_id_8bb368_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlike',
            index=models.Index(fields=['user', 'workout'], name='workouts_wo_user_id_ce1841_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutlike',
            unique_together={('user', 'workout')},
        ),
    ]
