# Generated by Django 5.1.2 on 2024-12-11 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_workouts_wo_user_id_dd8bda_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workoutlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutlike',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.AlterField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkoutComment',
        ),
        migrations.DeleteModel(
            name='WorkoutLike',
        ),
    ]
