# Generated by Django 5.1.2 on 2024-11-06 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_calories_alter_workout_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
