# Generated by Django 5.1.2 on 2024-11-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='calories',
        ),
    ]
