# Generated by Django 5.1.2 on 2024-11-17 11:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutcomment_workoutlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date_logged', '-created_at'], 'verbose_name': 'Workout', 'verbose_name_plural': 'Workouts'},
        ),
        migrations.AlterModelOptions(
            name='workoutcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout Comment', 'verbose_name_plural': 'Workout Comments'},
        ),
        migrations.AlterModelOptions(
            name='workoutlike',
            options={'verbose_name': 'Workout Like', 'verbose_name_plural': 'Workout Likes'},
        ),
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(default='My Workout', help_text='Title of the workout', max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date_logged',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], db_index=True, default='moderate', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('sports', 'Sports'), ('other', 'Other')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutcomment',
            name='content',
            field=models.TextField(help_text='Comment content'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date_logged'], name='workouts_wo_user_id_dd8bda_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['workout_type', 'intensity'], name='workouts_wo_workout_b4687e_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutcomment',
            index=models.Index(fields=['user', 'workout', 'created_at'], name='workouts_wo_user_id_8bb368_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlike',
            index=models.Index(fields=['user', 'workout'], name='workouts_wo_user_id_ce1841_idx'),
        ),
    ]
