# Generated by Django 5.1.2 on 2024-11-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('workouts', '0005_workoutcomment_workoutlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='caption',
        ),
        migrations.AlterField(
            model_name='workoutpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutpost',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workouts.workout'),
        ),
    ]
