# Generated by Django 5.1.2 on 2024-11-13 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_workoutpost_caption_alter_workoutpost_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutcomment',
            name='workout',
        ),
        migrations.AlterUniqueTogether(
            name='workoutlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workoutlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutlike',
            name='workout',
        ),
        migrations.AlterModelOptions(
            name='workoutpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout Post', 'verbose_name_plural': 'Workout Posts'},
        ),
        migrations.RenameField(
            model_name='workoutpost',
            old_name='shared_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='workoutpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workoutpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.workoutpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.workoutpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
        migrations.DeleteModel(
            name='WorkoutComment',
        ),
        migrations.DeleteModel(
            name='WorkoutLike',
        ),
    ]
